// export const difficulty = {
//     Easy: "a",
//     Medium: "b",
//     Hard: "c",
// };


// export const questionTypes = {
//     MCQ: "a",
//     "One Word/Sentence": "b",
//     "Fill in the blanks": "c",
//     "Match the following": "d",
// };


export const multilingualSupport = {
    "English": {
        "register": "Register",
        "login": "Login",
        "name": "Name",
        "employment": "Employment",
        "dragNDropProof": "Drag 'n' Drop or select a valid identity proof",
        "uploadPhotoID": "Uload Photo ID",
        "email": "Email Address",
        "userType": "User Type",
        "teacherType": "Teacher",
        "othersType": "Others",
        "schoolCollege": "School/College",
        "position": "Position",
        "password": "Password",
        "forgotPassword": "Forgot password?",
        "dontHaveAnAccountSignUp": "Don't have an account? Sign Up",
        "alreadyHaveAnAccountSignIn": "Already have an account? Sign in",

        "addQuestion": "Add Question",
        "searchQuestion": "Search Question",
        "generateQuestionPaper": "Generate Question Paper",

        "questionDetails": "Question Details",
        "board": "Board",
        "grade": "Grade",
        "questionType": "QuestionType",
        "mcq": "Multiple Choice Question",
        "oneWord": "One Word/Sentence",
        "fillInTheBlanks": "Fill in the Blanks",
        "matchTheFollowing": "Match the Following",
        "difficulty": "Difficulty",
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "mark": "Mark",
        "marks": "Marks",
        "subject": "Subject",
        "typeKeywordsAndPressEnter": "Type Keywords and Press Enter",
        "question": "Question",
        "numQuestions": "No. of questions",
        "key": "Key",
        "value": "Value",
        "addNew": "Add New",
        "remove": "Remove",
        "answer": "Answer",
        "answers": "Answers",
        "columnA": "Column A",
        "columnB": "Column B",
        "correctOption": "Correct Option",
        "wrongOpts": "Wrong Options",
        "wrongOption": "Type Wrong Options and Press Enter",
        "back": "Back",
        "next": "Next",

        "enterQuestion": "Enter Question",
        "enterQuestionSuccess": "Thank you for your Question.",
        "enterQuestionError": "OOPS! a similar question already exists!",
        "searchQuestion": "Search Question",
        "search": "Search",
        "exportPDF": "Export PDF",
        "reviewQuestion": "Review Question",
        "submitQuestion": "Submit Question",

        "invalidRegistration": "Invalid Registration Data! Please Try Again",
        "verifyEmail": "An email verification link has been sent on the given email address.\nPlease verify your email to complete the account setup.\nVerification link is valid for 24 hrs",

        "loginError1": "Invalid Login Credentials! Please Try Again",
        "loginError2": "Please validate your email! Check your inbox",

        "dashboard": "Dashboard",
        "viewIDProof": "View ID Proof",

        "changePassword": "Change Password",
        "changePasswordError": "Old password is incorrect. Please Try Again",
        "oldPassword": "Old Password",
        "newPassword": "New Password",
        "confirmNewPassword": "Confirm New Password",

        "logout": "Logout",
        "ok": "OK",
        "submit": "Submit",
        "change": "CHANGE",
        "backToHome": "Back to Home",
        "pageNotFound": "Page Not Found",

        "getResetLink": "Enter Email to Get your Password Reset Link",
        "enterNewPassword": "Enter your New Password",
        "resetPasswordAlertTitle": "Password Changed Successfully",
        "resetPasswordAlertDescription": "Your password has been reset successfully.\nPlease proceed to login",
        "resetPasswordError": "Reset Link has Expired! Please Try Again",

        "forgotPasswordError": "Invalid email ID! Please Try Again",
        "forgotPasswordAlertTitle": "Reset Password Link",
        "forgotPasswordAlertDescription": "A reset password link has been sent on the given email address.\nPlease click on the link to set your new password.\nReset link is valid for 24 hrs"
    },
    "Hindi": {
        'register': 'रजिस्टर करें',
        'login': 'लॉग इन करें',
        'name': 'उपनाम',
        'employment': 'रोज़गार',
        'dragNDropProof': 'एक वैध पहचान प्रमाण को खींचें और छोड़ें या चुनें',
        'uploadPhotoID': 'फोटो आईडी अपलोड करें',
        'email': 'ईमेल पता',
        'userType': 'उपयोगकर्ता का प्रकार',
        'teacherType': 'शिक्षक',
        'othersType': 'अन्य',
        'schoolCollege': 'स्कूल कॉलेज',
        'position': 'स्थान',
        'password': 'पासवर्ड',
        'forgotPassword': 'पासवर्ड भूल गए?',
        'dontHaveAnAccountSignUp': 'खाता नहीं है? साइन अप करें',
        'alreadyHaveAnAccountSignIn': 'क्या आपके पास पहले से एक खाता मौजूद है? साइन इन करें',
        'addQuestion': 'प्रश्न जोड़ें',
        'searchQuestion': 'खोज प्रश्न',
        'generateQuestionPaper': 'प्रश्न पत्र उत्पन्न करें',
        'questionDetails': 'प्रश्न विवरण',
        'board': 'मंडल',
        'grade': 'श्रेणी',
        'questionType': 'प्रश्न प्रकार',
        'mcq': 'बहु विकल्पीय प्रश्न',
        'oneWord': 'एक शब्द/वाक्य',
        'fillInTheBlanks': 'रिक्त स्थान भरें',
        'matchTheFollowing': 'निम्नलिखित को मिलाएं',
        'difficulty': 'कठिनाई',
        'easy': 'आसान',
        'medium': 'मध्यम',
        'hard': 'कठिन',
        'mark': 'निशान',
        'marks': 'निशान',
        'subject': 'विषय',
        'typeKeywordsAndPressEnter': 'कीवर्ड टाइप करें और एंटर दबाएं',
        'question': 'प्रश्न',
        'numQuestions': 'प्रश्नों की संख्या',
        'key': 'चाभी',
        'value': 'मूल्य',
        'addNew': 'नया जोड़ो',
        'remove': 'हटाना',
        'answer': 'उत्तर',
        'answers': 'जवाब',
        'columnA': 'कॉलम ए',
        'columnB': 'कॉलम बी',
        'correctOption': 'सही विकल्प',
        'wrongOpts': 'गलत विकल्प',
        'wrongOption': 'गलत विकल्प टाइप करें और एंटर दबाएं',
        'back': 'पीछे',
        'next': 'अगला',
        'enterQuestion': 'प्रश्न दर्ज करें',
        'enterQuestionSuccess': 'आपके सवाल के लिए धन्यवाद।',
        'enterQuestionError': 'उफ़! ऐसा ही एक प्रश्न पहले से मौजूद है!',
        'search': 'खोज',
        'exportPDF': 'पीडीएफ निर्यात करें',
        'reviewQuestion': 'समीक्षा प्रश्न',
        'submitQuestion': 'प्रश्न सबमिट करें',
        'invalidRegistration': 'अमान्य पंजीकरण डेटा! कृपया पुन: प्रयास करें',
        'verifyEmail': 'दिए गए ईमेल पते पर एक ईमेल सत्यापन लिंक भेजा गया है।\nखाता सेटअप पूरा करने के लिए कृपया अपना ईमेल सत्यापित करें।\nसत्यापन लिंक 24 घंटे के लिए वैध है',
        'loginError1': 'अमान्य प्रवेश करना प्रत्यायक! कृपया पुन: प्रयास करें',
        'loginError2': 'कृपया अपना ईमेल सत्यापित करें! अपने इनबॉक्स की जाँच करें',
        'dashboard': 'डैशबोर्ड',
        'viewIDProof': 'आईडी प्रमाण देखें',
        'changePassword': 'पासवर्ड बदलें',
        'changePasswordError': 'पुराना पासवर्ड गलत है। कृपया पुन: प्रयास करें',
        'oldPassword': 'पुराना पासवर्ड',
        'newPassword': 'नया पासवर्ड',
        'confirmNewPassword': 'नए पासवर्ड की पुष्टि करें',
        'logout': 'लॉग आउट',
        'ok': 'ठीक है',
        'submit': 'प्रस्तुत करना',
        'change': 'परिवर्तन',
        'backToHome': 'मुखपृष्ठ पर वापस',
        'pageNotFound': 'पृष्ठ नहीं मिला',
        'getResetLink': 'अपना पासवर्ड रीसेट लिंक प्राप्त करने के लिए ईमेल दर्ज करें',
        'enterNewPassword': 'अपना नया पासवर्ड दर्ज करें',
        'resetPasswordAlertTitle': 'पासवर्ड सफलतापूर्वक बदला गया',
        'resetPasswordAlertDescription': 'आपका पासवर्ड सफलतापूर्वक रीसेट कर दिया गया है।\nकृपया लॉगिन करने के लिए आगे बढ़ें',
        'resetPasswordError': 'रीसेट लिंक की समय सीमा समाप्त हो गई है! कृपया पुन: प्रयास करें',
        'forgotPasswordError': 'अमान्य ईमेल आईडी! कृपया पुन: प्रयास करें',
        'forgotPasswordAlertTitle': 'पासवर्ड लिंक रीसेट करें',
        'forgotPasswordAlertDescription': 'दिए गए ईमेल पते पर एक रीसेट पासवर्ड लिंक भेजा गया है।\nअपना नया पासवर्ड सेट करने के लिए कृपया लिंक पर क्लिक करें।\nरीसेट लिंक 24 घंटे के लिए वैध है'
    },
    "Gujarati": {
        'register': 'નોંધણી કરો',
        'login': 'પ્રવેશ કરો',
        'name': 'અટક',
        'employment': 'રોજગાર',
        'dragNDropProof': 'ખેંચો અને છોડો અથવા માન્ય ઓળખ પુરાવો પસંદ કરો',
        'uploadPhotoID': 'ફોટો ID અપલોડ કરો',
        'email': 'ઈ - મેઈલ સરનામું',
        'userType': 'વપરાશકર્તા પ્રકાર',
        'teacherType': 'શિક્ષક',
        'othersType': 'અન્ય',
        'schoolCollege': 'શાળા/કોલેજ',
        'position': 'પદ',
        'password': 'પાસવર્ડ',
        'forgotPassword': 'પાસવર્ડ ભૂલી ગયા છો?',
        'dontHaveAnAccountSignUp': 'ખાતું નથી? સાઇન અપ કરો',
        'alreadyHaveAnAccountSignIn': 'પહેલેથી એકાઉન્ટ છે? સાઇન ઇન કરો',
        'addQuestion': 'પ્રશ્ન ઉમેરો',
        'searchQuestion': 'પ્રશ્ન શોધો',
        'generateQuestionPaper': 'પ્રશ્નપત્ર જનરેટ કરો',
        'questionDetails': 'પ્રશ્નોની વિગતો',
        'board': 'પાટીયું',
        'grade': 'ગ્રીડ',
        'questionType': 'પ્રશ્નપ્રકાર',
        'mcq': 'બહુવિધ પસંદગીના પ્રશ્નો',
        'oneWord': 'એક શબ્દ/વાક્ય',
        'fillInTheBlanks': 'ખાલી જગ્યા પૂરો',
        'matchTheFollowing': 'નીચેના સાથે મેળ કરો',
        'difficulty': 'મુશ્કેલી',
        'easy': 'સરળ',
        'medium': 'મધ્યમ',
        'hard': 'સખત',
        'mark': 'ચિહ્ન',
        'marks': 'ગુણ',
        'subject': 'વિષય',
        'typeKeywordsAndPressEnter': 'કીવર્ડ્સ ટાઈપ કરો અને એન્ટર દબાવો',
        'question': 'પ્રશ્ન',
        'numQuestions': 'પ્રશ્નોની સંખ્યા',
        'key': 'કી',
        'value': 'મૂલ્ય',
        'addNew': 'નવો ઉમેરો',
        'remove': 'દૂર કરો',
        'answer': 'જવાબ આપો',
        'answers': 'જવાબો',
        'columnA': 'કૉલમ એ',
        'columnB': 'કૉલમ B',
        'correctOption': 'સાચો વિકલ્પ',
        'wrongOpts': 'ખોટા વિકલ્પો',
        'wrongOption': 'ખોટા વિકલ્પો લખો અને એન્ટર દબાવો',
        'back': 'પાછળ',
        'next': 'આગળ',
        'enterQuestion': 'પ્રશ્ન દાખલ કરો',
        'enterQuestionSuccess': 'તમારા પ્રશ્ન બદલ આભાર.',
        'enterQuestionError': 'અરે! એક સમાન પ્રશ્ન પહેલેથી અસ્તિત્વમાં છે!',
        'search': 'શોધો',
        'exportPDF': 'પીડીએફ નિકાસ કરો',
        'reviewQuestion': 'પ્રશ્નની સમીક્ષા કરો',
        'submitQuestion': 'પ્રશ્ન સબમિટ કરો',
        'invalidRegistration': 'અમાન્ય નોંધણી ડેટા! મહેરબાની કરીને ફરીથી પ્રયતન કરો',
        'verifyEmail': 'આપેલ ઈમેલ એડ્રેસ પર ઈમેલ વેરિફિકેશન લિંક મોકલવામાં આવી છે.\nએકાઉન્ટ સેટઅપ પૂર્ણ કરવા માટે કૃપા કરીને તમારી ઇમેઇલ ચકાસો.\nચકાસણી લિંક 24 કલાક માટે માન્ય છે',
        'loginError1': 'અમાન્ય લૉગિન ઓળખપત્રો! મહેરબાની કરીને ફરીથી પ્રયતન કરો',
        'loginError2': 'કૃપા કરીને તમારા ઇમેઇલને માન્ય કરો! તમારું ઇનબોક્સ તપાસો',
        'dashboard': 'ડેશબોર્ડ',
        'viewIDProof': 'ID પ્રૂફ જુઓ',
        'changePassword': 'પાસવર્ડ બદલો',
        'changePasswordError': 'જૂનો પાસવર્ડ ખોટો છે. મહેરબાની કરીને ફરીથી પ્રયતન કરો',
        'oldPassword': 'જુનો પાસવર્ડ',
        'newPassword': 'નવો પાસવર્ડ',
        'confirmNewPassword': 'નવાપાસવર્ડની પુષ્ટી કરો',
        'logout': 'લૉગ આઉટ',
        'ok': 'બરાબર',
        'submit': 'સબમિટ કરો',
        'change': 'બદલો',
        'backToHome': 'હોમ પેજ પર પાછા',
        'pageNotFound': 'પેજ નથી મળ્યું',
        'getResetLink': 'તમારો પાસવર્ડ રીસેટ લિંક મેળવવા માટે ઈમેલ દાખલ કરો',
        'enterNewPassword': 'તમારો નવો પાસવર્ડ દાખલ કરો',
        'resetPasswordAlertTitle': 'પાસવર્ડ સફળતાપૂર્વક બદલાયો',
        'resetPasswordAlertDescription': 'તમારો પાસવર્ડ સફળતાપૂર્વક રીસેટ કરવામાં આવ્યો છે.\nકૃપા કરીને લૉગિન કરવા માટે આગળ વધો',
        'resetPasswordError': 'રીસેટ લિંકની સમયસીમા સમાપ્ત થઈ ગઈ છે! મહેરબાની કરીને ફરીથી પ્રયતન કરો',
        'forgotPasswordError': 'અમાન્ય ઇમેઇલ ID! મહેરબાની કરીને ફરીથી પ્રયતન કરો',
        'forgotPasswordAlertTitle': 'પાસવર્ડ લિંક રીસેટ કરો',
        'forgotPasswordAlertDescription': 'આપેલ ઈમેલ એડ્રેસ પર રીસેટ પાસવર્ડ લિંક મોકલવામાં આવી છે.\nતમારો નવો પાસવર્ડ સેટ કરવા માટે કૃપા કરીને લિંક પર ક્લિક કરો.\nરીસેટ લિંક 24 કલાક માટે માન્ય છે'
    },
    "Marathi": {
        'register': 'नोंदणी करा',
        'login': 'लॉगिन करा',
        'name': 'आडनाव',
        'employment': 'रोजगार',
        'dragNDropProof': 'ड्रॅग आणि ड्रॉप करा किंवा वैध ओळख पुरावा निवडा',
        'uploadPhotoID': 'फोटो आयडी अपलोड करा',
        'email': 'ईमेल पत्ता',
        'userType': 'वापरकर्ता प्रकार',
        'teacherType': 'शिक्षक',
        'othersType': 'इतर',
        'schoolCollege': 'शाळा/कॉलेज',
        'position': 'स्थिती',
        'password': 'पासवर्ड',
        'forgotPassword': 'पासवर्ड विसरलात?',
        'dontHaveAnAccountSignUp': 'खाते नाही? साइन अप करा',
        'alreadyHaveAnAccountSignIn': 'आधीपासूनच एक खाते आहे? साइन इन करा',
        'addQuestion': 'प्रश्न जोडा',
        'searchQuestion': 'शोध प्रश्न',
        'generateQuestionPaper': 'प्रश्नपत्रिका तयार करा',
        'questionDetails': 'प्रश्न तपशील',
        'board': 'बोर्ड',
        'grade': 'ग्रिड',
        'questionType': 'प्रश्नप्रकार',
        'mcq': 'एकाधिक निवड प्रश्न',
        'oneWord': 'एक शब्द/वाक्य',
        'fillInTheBlanks': 'रिक्त स्थानांची पुरती करा',
        'matchTheFollowing': 'खालील जुळवा',
        'difficulty': 'अडचण',
        'easy': 'सोपे',
        'medium': 'मध्यम',
        'hard': 'कठीण',
        'mark': 'खूण करा',
        'marks': 'मार्क्स',
        'subject': 'विषय',
        'typeKeywordsAndPressEnter': 'कीवर्ड टाइप करा आणि एंटर दाबा',
        'question': 'प्रश्न',
        'numQuestions': 'प्रश्नांची संख्या',
        'key': 'की',
        'value': 'मूल्य',
        'addNew': 'नवीन जोडा',
        'remove': 'काढा',
        'answer': 'उत्तर द्या',
        'answers': 'उत्तरे',
        'columnA': 'स्तंभ ए',
        'columnB': 'स्तंभ बी',
        'correctOption': 'योग्य पर्याय',
        'wrongOpts': 'चुकीचे पर्याय',
        'wrongOption': 'चुकीचे पर्याय टाइप करा आणि एंटर दाबा',
        'back': 'मागे',
        'next': 'पुढे',
        'enterQuestion': 'प्रश्न प्रविष्ट करा',
        'enterQuestionSuccess': 'तुमच्या प्रश्नाबद्दल धन्यवाद.',
        'enterQuestionError': 'अरेरे! एक समान प्रश्न आधीच अस्तित्वात आहे!',
        'search': 'शोधा',
        'exportPDF': 'पीडीएफ निर्यात करा',
        'reviewQuestion': 'प्रश्नाचे पुनरावलोकन करा',
        'submitQuestion': 'प्रश्न सबमिट करा',
        'invalidRegistration': 'अवैध नोंदणी डेटा! कृपया पुन्हा प्रयत्न करा',
        'verifyEmail': 'दिलेल्या ईमेल पत्त्यावर ईमेल पडताळणी लिंक पाठवली आहे.\nखाते सेटअप पूर्ण करण्यासाठी कृपया तुमचा ईमेल सत्यापित करा.\nपडताळणी लिंक २४ तासांसाठी वैध आहे',
        'loginError1': 'अवैध लॉगिन क्रेडेन्शियल! कृपया पुन्हा प्रयत्न करा',
        'loginError2': 'कृपया तुमचा ईमेल सत्यापित करा! आपला इनबॉक्स तपासा',
        'dashboard': 'डॅशबोर्ड',
        'viewIDProof': 'आयडी प्रूफ पहा',
        'changePassword': 'पासवर्ड बदला',
        'changePasswordError': 'जुना पासवर्ड चुकीचा आहे. कृपया पुन्हा प्रयत्न करा',
        'oldPassword': 'जुना पासवर्ड',
        'newPassword': 'नवीन पासवर्ड',
        'confirmNewPassword': 'नवीन परवलीच्या शब्दाची खात्री करा',
        'logout': 'बाहेर पडणे',
        'ok': 'ठीक आहे',
        'submit': 'प्रस्तुत करणे',
        'change': 'बदला',
        'backToHome': 'मुख्यपृष्ठावर परत',
        'pageNotFound': 'पृष्ठ सापडले नाही',
        'getResetLink': 'तुमचा पासवर्ड रिसेट लिंक मिळवण्यासाठी ईमेल एंटर करा',
        'enterNewPassword': 'तुमचा नवीन पासवर्ड टाका',
        'resetPasswordAlertTitle': 'पासवर्ड यशस्वीरित्या बदलला',
        'resetPasswordAlertDescription': 'तुमचा पासवर्ड यशस्वीरित्या रीसेट केला गेला आहे.\nकृपया लॉग इन करण्यासाठी पुढे जा',
        'resetPasswordError': 'रीसेट लिंक कालबाह्य झाली आहे! कृपया पुन्हा प्रयत्न करा',
        'forgotPasswordError': 'अवैध ईमेल आयडी! कृपया पुन्हा प्रयत्न करा',
        'forgotPasswordAlertTitle': 'पासवर्ड लिंक रीसेट करा',
        'forgotPasswordAlertDescription': 'दिलेल्या ईमेल पत्त्यावर पासवर्ड रीसेट करण्याची लिंक पाठवली आहे.\nतुमचा नवीन पासवर्ड सेट करण्यासाठी कृपया लिंकवर क्लिक करा.\nरीसेट लिंक 24 तासांसाठी वैध आहे'
    }
}