export const difficulty = {
    Easy: "a",
    Medium: "b",
    Hard: "c",
};

export const questionTypes = {
    MCQ: "a",
    "One Word/Sentence": "b",
    "Fill in the blanks": "c",
    "Match the following": "d",
};


export const multilingualSupport = {
    "English": {
        "register": "Register",
        "login": "Login",
        "name": "Name",
        "employment": "Employment",
        "dragNDropProof": "Drag 'n' Drop or select a valid identity proof",
        "uploadPhotoID": "Uload Photo ID",
        "email": "Email Address",
        "userType": "User Type",
        "teacherType": "Teacher",
        "othersType": "Others",
        "schoolCollege": "School/College",
        "position": "Position",
        "password": "Password",
        "forgotPassword": "Forgot password?",
        "dontHaveAnAccountSignUp": "Don't have an account? Sign Up",
        "alreadyHaveAnAccountSignIn": "Already have an account? Sign in",

        "addQuestion": "Add Question",
        "searchQuestion": "Search Question",
        "generateQuestionPaper": "Generate Question Paper",

        "questionDetails": "Question Details",
        "board": "Board",
        "grade": "Grade",
        "questionType": "QuestionType",
        "mcq": "Multiple Choice Question",
        "oneWord": "One Word/Sentence",
        "fillInTheBlanks": "Fill in the Blanks",
        "matchTheFollowing": "Match the Following",
        "difficulty": "Difficulty",
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "mark": "Mark",
        "marks": "Marks",
        "subject": "Subject",
        "typeKeywordsAndPressEnter": "Type Keywords and Press Enter",
        "question": "Question",
        "numQuestions": "No. of questions",
        "key": "Key",
        "value": "Value",
        "addNew": "Add New",
        "remove": "Remove",
        "answer": "Answer",
        "answers": "Answers",
        "columnA": "Column A",
        "columnB": "Column B",
        "correctOption": "Correct Option",
        "wrongOption": "Type Wrong Options and Press Enter",
        "back": "Back",
        "next": "Next",

        "enterQuestion": "Enter Question",
        "searchQuestion": "Search Question",
        "search": "Search",
        "exportPDF": "Export PDF",
        "reviewQuestion": "Review Question",
        "submitQuestion": "Submit Question",

        "invalidRegistration": "Invalid Registration Data! Please Try Again",
        "verifyEmail": "An email verification link has been sent on the given email address.\nPlease verify your email to complete the account setup.\nVerification link is valid for 24 hrs",

        "loginError1": "Invalid Login Credentials! Please Try Again",
        "loginError2": "Please validate your email! Check your inbox",

        "dashboard": "Dashboard",
        "viewIDProof": "View ID Proof",

        "changePassword": "Change Password",
        "changePasswordError": "Old password is incorrect. Please Try Again",
        "oldPassword": "Old Password",
        "newPassword": "New Password",
        "confirmNewPassword": "Confirm New Password",

        "logout": "Logout",
        "ok": "OK",
        "submit": "Submit",
        "change": "CHANGE",
        "backToHome": "Back to Home",
        "pageNotFound": "Page Not Found",

        "getResetLink": "Enter Email to Get your Password Reset Link",
        "enterNewPassword": "Enter your New Password",
        "resetPasswordAlertTitle": "Password Changed Successfully",
        "resetPasswordAlertDescription": "Your password has been reset successfully.\nPlease proceed to login",
        "resetPasswordError": "Reset Link has Expired! Please Try Again",

        "forgotPasswordError": "Invalid email ID! Please Try Again",
        "forgotPasswordAlertTitle": "Reset Password Link",
        "forgotPasswordAlertDescription": "A reset password link has been sent on the given email address.\nPlease click on the link to set your new password.\nReset link is valid for 24 hrs"
    },
    "Hindi": {
        'register': 'रजिस्टर करें',
        'login': 'लॉग इन करें',
        'name': 'उपनाम',
        'employment': 'रोज़गार',
        'dragNDropProof': "'n' ड्रॉप खींचें या एक मान्य पहचान प्रमाण चुनें",
        'uploadPhotoID': 'फोटो आईडी अपलोड करें',
        'email': 'ईमेल पता',
        'userType': 'उपयोगकर्ता का प्रकार',
        'teacherType': 'शिक्षक',
        'othersType': 'अन्य',
        'schoolCollege': 'स्कूल कॉलेज',
        'position': 'स्थान',
        'password': 'पासवर्ड',
        'forgotPassword': 'पासवर्ड भूल गए?',
        'dontHaveAnAccountSignUp': 'खाता नहीं है? साइन अप करें',
        'alreadyHaveAnAccountSignIn': 'क्या आपके पास पहले से एक खाता मौजूद है? साइन इन करें',
        'addQuestion': 'प्रश्न जोड़ें',
        'searchQuestion': 'खोज प्रश्न',
        'generateQuestionPaper': 'प्रश्न पत्र उत्पन्न करें',
        'questionDetails': 'प्रश्न विवरण',
        'board': 'तख्ता',
        'grade': 'जाल',
        'questionType': 'प्रश्न प्रकार',
        'mcq': 'बहु विकल्पीय प्रश्न',
        'oneWord': 'एक शब्द/वाक्य',
        'fillInTheBlanks': 'रिक्त स्थान भरें',
        'matchTheFollowing': 'निम्नलिखित को मिलाएं',
        'difficulty': 'कठिनाई',
        'easy': 'आसान',
        'medium': 'मध्यम',
        'hard': 'कठिन',
        'marks': 'निशान',
        'subject': 'विषय',
        'typeKeywordsAndPressEnter': 'कीवर्ड टाइप करें और एंटर दबाएं',
        'question': 'प्रश्न',
        'key': 'चाभी',
        'value': 'मूल्य',
        'addNew': 'नया जोड़ो',
        'remove': 'हटाना',
        'answer': 'उत्तर',
        'correctOption': 'सही विकल्प',
        'wrongOption': 'गलत विकल्प टाइप करें और एंटर दबाएं',
        'back': 'पीछे',
        'next': 'अगला',
        'enterQuestion': 'प्रश्न दर्ज करें',
        'search': 'खोज',
        'reviewQuestion': 'समीक्षा प्रश्न',
        'submitQuestion': 'प्रश्न सबमिट करें',
        'invalidRegistration': 'अमान्य पंजीकरण डेटा! कृपया पुन: प्रयास करें',
        'verifyEmail': 'दिए गए ईमेल पते पर एक ईमेल सत्यापन लिंक भेजा गया है।\nखाता सेटअप पूरा करने के लिए कृपया अपना ईमेल सत्यापित करें।\nसत्यापन लिंक 24 घंटे के लिए वैध है',
        'loginError1': 'अमान्य प्रवेश करना प्रत्यायक! कृपया पुन: प्रयास करें',
        'loginError2': 'कृपया अपना ईमेल सत्यापित करें! अपने इनबॉक्स की जाँच करें',
        'dashboard': 'डैशबोर्ड',
        'viewIDProof': 'आईडी प्रमाण देखें',
        'changePassword': 'पासवर्ड बदलें',
        'changePasswordError': 'पुराना पासवर्ड गलत है। कृपया पुन: प्रयास करें',
        'oldPassword': 'पुराना पासवर्ड',
        'newPassword': 'नया पासवर्ड',
        'confirmNewPassword': 'नए पासवर्ड की पुष्टि करें',
        'logout': 'लॉग आउट',
        'ok': 'ठीक है',
        'submit': 'प्रस्तुत करना',
        'change': 'परिवर्तन',
        'backToHome': 'घर वापिस जा रहा हूँ',
        'pageNotFound': 'पृष्ठ नहीं मिला',
        'getResetLink': 'अपना पासवर्ड रीसेट लिंक प्राप्त करने के लिए ईमेल दर्ज करें',
        'enterNewPassword': 'अपना नया पासवर्ड दर्ज करें',
        'resetPasswordAlertTitle': 'पासवर्ड सफलतापूर्वक बदला गया',
        'resetPasswordAlertDescription': 'आपका पासवर्ड सफलतापूर्वक रीसेट कर दिया गया है।\nकृपया लॉगिन करने के लिए आगे बढ़ें',
        'resetPasswordError': 'रीसेट लिंक की समय सीमा समाप्त हो गई है! कृपया पुन: प्रयास करें',
        'forgotPasswordError': 'अमान्य ईमेल आईडी! कृपया पुन: प्रयास करें',
        'forgotPasswordAlertTitle': 'पासवर्ड लिंक रीसेट करें',
        'forgotPasswordAlertDescription': 'दिए गए ईमेल पते पर एक रीसेट पासवर्ड लिंक भेजा गया है।\nअपना नया पासवर्ड सेट करने के लिए कृपया लिंक पर क्लिक करें।\nरीसेट लिंक 24 घंटे के लिए वैध है'
    }
}